# Generated by Django 3.1.3 on 2021-03-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
