# Generated by Django 3.1.3 on 2021-03-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210306_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
