# Generated by Django 3.1.3 on 2021-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210306_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, default='blog/default.png', upload_to='blog'),
        ),
    ]
