# Generated by Django 3.1.3 on 2021-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210306_2216'),
        ('account', '0002_auto_20210307_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='product.Product'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='product.Product'),
        ),
    ]
