# Generated by Django 3.1.3 on 2021-03-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210306_2216'),
        ('account', '0003_auto_20210311_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pic',
            field=models.ImageField(blank=True, default='account/default.png', upload_to='account'),
        ),
    ]
