# Generated by Django 3.1.3 on 2021-03-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210311_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('CA', 'Canada'), ('UA', 'Ukraine')], max_length=2),
        ),
    ]
