# Generated by Django 3.1.3 on 2021-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210305_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='top_selling',
            field=models.BooleanField(default=False),
        ),
    ]
