# Generated by Django 3.1.3 on 2021-03-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210305_2212'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='product.product'),
            preserve_default=False,
        ),
    ]
