# Generated by Django 3.1.3 on 2021-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210306_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
